version: "3.9"

services:
  streamlit:
    build:
      context: .
    restart: always
    volumes:
      - ./.streamlit:/app/.streamlit/
      - ./weatherdashboard:/app/weatherdashboard/
    command: ["streamlit", "run", "weatherdashboard/dashboard.py"]
    ports:
      - 8501:8501

    stdin_open: true
    tty: true
