[tool.poetry]
name = "weatherteam-streamlit-dashboard"
version = "0.1.0"
description = "Streamlit dashboard project to visualize weather data"
authors = ["donatien konan <donatien.konan.pro@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.9.7 || >3.9.7,<3.13"
streamlit = "1.18.1"
altair = "4.2.2"
pandas = "2.0.3"
sqlalchemy = "2.0.37"
google-oauth2-tool = "0.0.3"
ipython = "8.12.1"
protobuf = "==3.20.*"
google-cloud = "^0.34.0"
google-cloud-bigquery = "3.21.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
