[tool.poetry]
name = "weatherteam-streamlit-dashboard"
version = "0.1.0"
description = "Streamlit dashboard project to visualize weather data"
authors = ["donatien konan <donatien.konan.pro@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.13"
streamlit = "1.3.0"
altair = "5.4.1"
pandas = "2.0.3"
sqlalchemy = "2.0.37"
google-oauth2-tool = "0.0.3"
ipython = "8.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
